export type Building = {
  slug: string;
  name: string;
  profile: string;
  area: string;
  summary: string;
  status: 'completed' | 'in-development' | 'verify-delivery';
  buyerFit: string;
  buyerCheck: string;
  statusSource?: { label: string; url: string };
  confirmed: string[];
  questions: string[];
  source: { label: string; url: string };
};

// Only cite the linked project/operator source for the public statements here.
// Do not infer a completion date, current availability, HOA, pet or rental policy.
export const buildings: Building[] = [
  { slug:'echo-brickell', name:'Echo Brickell', profile:'Residential tower', area:'Brickell Avenue', status:'completed', buyerFit:'Compare it if an established tower on Brickell Avenue fits your search.', buyerCheck:'Confirm the specific unit’s parking rights and current association budget.', summary:'A residential high-rise on the east side of Brickell Avenue. The developer describes it as a 60-story tower.', confirmed:['The JDS Development portfolio identifies Echo Brickell as a residential project on the east side of Brickell Avenue.','Its published tower profile emphasizes residential design and shared amenities; actual unit features must be checked individually.'], questions:['What is the present association budget and reserve study?','Which parking and storage rights belong to the unit?','What do the current rental and pet rules say?'], source:{label:'JDS Development, Echo Brickell project',url:'https://jdsdevelopment.com/portfolio/echo-brickell'} },
  { slug:'brickell-flatiron', name:'Brickell Flatiron', profile:'Residential tower', area:'Brickell core', status:'completed', buyerFit:'Compare it if walking access to central Brickell matters to you.', buyerCheck:'Visit at different hours to judge street noise and check current association records.', summary:'A condominium project by CMC Group in central Brickell.', confirmed:['CMC Group lists Brickell Flatiron among its Miami projects.','The building’s central location makes walking routes and street activity useful visit-day checks.'], questions:['Which association financials and inspection records are current?','How do the floor and line affect the view and noise?','What rules apply to this specific intended use?'], source:{label:'CMC Group, Brickell Flatiron',url:'https://www.cmcgroupmiami.com/projects/brickell-flatiron.html'} },
  { slug:'sls-lux', name:'SLS LUX Brickell', profile:'Luxury condominium', area:'Central Brickell', status:'completed', buyerFit:'Compare it if you want to assess a condominium close to Brickell City Centre.', buyerCheck:'Verify which services and amenities the specific legal unit may use.', summary:'A Related Group condominium project near Brickell City Centre; specific residence rights and amenities need document review.', confirmed:['Related Group identifies SLS LUX as a luxury condominium in Brickell.','The developer highlights its proximity to Brickell City Centre and designer-led interiors.'], questions:['What services and costs apply to this legal unit?','Which amenities are available under current association rules?','What do current rental and pet documents permit?'], source:{label:'Related Group, SLS LUX project',url:'https://relatedgroup.com/properties/sls-lux/'} },
  { slug:'four-seasons-residences', name:'Four Seasons Residences Miami', profile:'Private residences', area:'Brickell Avenue', status:'completed', buyerFit:'Compare it if private residences with hotel-adjacent services interest you.', buyerCheck:'Get written confirmation of service access, fees and shared-facility rules.', summary:'Four Seasons identifies a Miami private-residences component; specific unit rights require written confirmation.', confirmed:['Four Seasons describes a private residential tower in central Miami.','Its residence page notes 186 private residences; individual resale availability is not verified here.'], questions:['Which service access is included for this unit?','What do condominium documents say about assessments and reserves?','How are hotel and residential facilities governed?'], source:{label:'Four Seasons Private Residences Miami',url:'https://www.fourseasons.com/residences/private_residences/miami/'} },
  { slug:'una-residences', name:'Una Residences', profile:'Waterfront development', area:'South Brickell waterfront', status:'completed', buyerFit:'Compare it if a recently completed waterfront building fits your search.', buyerCheck:'Review flood exposure, insurance and the unit’s current association costs.', statusSource:{label:'OKO Group portfolio: Completed',url:'https://www.okogroup.com/portfolio/una-residences'}, summary:'A Brickell waterfront residential project with architecture promoted by the project website.', confirmed:['The project site identifies Adrian Smith + Gordon Gill Architecture as the design firm.','Project materials describe its waterfront Brickell setting.'], questions:['What is the current construction and delivery status?','Which features and fees are binding in the offering documents?','How will the specific unit’s exposure and flood insurance be assessed?'], source:{label:'Una Residences project site',url:'https://www.unaresidences.com/'} },
  { slug:'cipriani-residences-miami', name:'Cipriani Residences Miami', profile:'Branded residential development', area:'South Miami Avenue', status:'in-development', buyerFit:'Compare it if your move-in timeline can accommodate a developing project.', buyerCheck:'Confirm occupancy timing, deposits and what the offering documents actually guarantee.', statusSource:{label:'Cipriani official project: occupancy target',url:'https://ciprianiresidencesmiami.com/'}, summary:'A Cipriani branded residential project at the gateway to Brickell; published features may change during development.', confirmed:['The project website locates the development in Brickell and describes a hospitality-led residential concept.','Its contact page publishes the address 1420 South Miami Avenue.'], questions:['What is the current construction and contractual delivery position?','What services are included versus separately charged?','What do the final offering documents say about the residence?'], source:{label:'Cipriani Residences Miami project site',url:'https://ciprianiresidencesmiami.com/'} },
  { slug:'viceroy-brickell', name:'Viceroy Brickell Residences', profile:'Branded residential development', area:'Central Brickell', status:'verify-delivery', buyerFit:'Compare it if a branded residence in central Brickell fits your search.', buyerCheck:'Confirm current occupancy status and unit rights in writing before planning a move.', summary:'A Viceroy branded residential concept in central Brickell with proposed shared amenities.', confirmed:['The project site identifies its location as Brickell.','Published concept materials describe a pool, wellness spaces and social amenities.'], questions:['Are the proposed amenities finalized in the offering documents?','What are the current budget and completion milestones?','What are the actual unit-level service rights and fees?'], source:{label:'Viceroy Brickell Residences, official developer site',url:'https://viceroybrickellresidences.com/'} },
  { slug:'baccarat-residences-miami', name:'Baccarat Residences Miami', profile:'Waterfront residential development', area:'Brickell riverfront', status:'in-development', buyerFit:'Compare it if a riverfront project and a flexible delivery timeline suit you.', buyerCheck:'Confirm construction milestones, deposits and waterfront insurance assumptions.', statusSource:{label:'Related Group: Baccarat project',url:'https://relatedgroup.com/properties/baccarat/'}, summary:'A Baccarat branded residential project positioned by its materials near the Miami River and Biscayne Bay.', confirmed:['The developer project site describes a Brickell waterfront residence collection where the river meets the bay.','Its legal notice says the offering is governed by the developer prospectus; website descriptions are not contractual.'], questions:['What is the confirmed construction and delivery status?','How will waterfront exposure and insurance affect ownership cost?','Which amenities and rights are contractual for the unit?'], source:{label:'Baccarat Residences Miami developer site',url:'https://baccaratresidencesmiami.com/'} }
];

export const buildingBySlug = Object.fromEntries(buildings.map(b => [b.slug, b])) as Record<string, Building>;
