export type Building = {
  slug: string;
  name: string;
  profile: string;
  area: string;
  summary: string;
  confirmed: string[];
  questions: string[];
  source: { label: string; url: string };
};

// Only cite the linked project/operator source for the public statements here.
// Do not infer a completion date, current availability, HOA, pet or rental policy.
export const buildings: Building[] = [

  { slug:'reach-brickell-city-centre', name:'Reach at Brickell City Centre', profile:'Mixed-use district residence', area:'Brickell City Centre', summary:'A Swire Properties residential component of Brickell City Centre; examine district access and unit-level rights.', confirmed:['Swire Properties lists Reach as a residential development in Brickell City Centre.','Its published profile places the residences within the mixed-use district.'], questions:['Which parking and amenity rights attach to this unit?','What do current association documents say about fees and reserves?','How does the actual entrance work for your daily routes?'], source:{label:'Swire Properties, Reach',url:'https://www.swireproperties.com/en/portfolio/past-developments/reach/'} },
  { slug:'rise-brickell-city-centre', name:'Rise at Brickell City Centre', profile:'Mixed-use district residence', area:'Brickell City Centre', summary:'A Swire Properties residential component of Brickell City Centre; compare floor, access and ownership costs.', confirmed:['Swire Properties identifies Rise as part of its Brickell City Centre development.','The official portfolio describes it as a residential project.'], questions:['Which amenities and parking rights are documented for the unit?','How do the actual line and floor affect noise and views?','Are current reserves and assessment records available?'], source:{label:'Swire Properties, Rise',url:'https://www.swireproperties.com/en/portfolio/past-developments/rise/'} },
  { slug:'brickell-key-one', name:'Brickell Key One', profile:'Island condominium', area:'Brickell Key', summary:'A Swire Properties residential project on Brickell Key; compare island access with unit-level costs.', confirmed:['Swire Properties lists Brickell Key One among its Brickell Key developments.','The developer portfolio identifies it as a residential project.'], questions:['What are current reserve and assessment records?','What view and parking rights belong to the exact unit?','How do the current pet and rental rules apply?'], source:{label:'Swire Properties, Brickell Key One',url:'https://www.swireproperties.com/en/portfolio/past-developments/brickell-key-one/'} },
  { slug:'courts-brickell-key', name:'Courts Brickell Key', profile:'Island condominium', area:'Brickell Key', summary:'A Brickell Key residential development in Swire Properties’ portfolio; inspect actual unit rights and financials.', confirmed:['Swire Properties identifies Courts Brickell Key in its island development portfolio.','Its portfolio describes the project as residential.'], questions:['What do the current inspection and reserve records show?','Which unit-specific parking and storage rights exist?','What is the actual island commute at your travel time?'], source:{label:'Swire Properties, Courts Brickell Key',url:'https://www.swireproperties.com/en/portfolio/past-developments/courts-brickell-key/'} },
  { slug:'courvoisier-courts', name:'Courvoisier Courts', profile:'Island condominium', area:'Brickell Key', summary:'A Swire Properties Brickell Key residential project; verify fees, exposure and current rules for a candidate unit.', confirmed:['Swire Properties includes Courvoisier Courts in its portfolio of Brickell Key projects.','The official project page describes residential development on the island.'], questions:['What are current association fees and approved assessments?','How does the specific unit face the water and nearby properties?','What do the present rental and pet rules permit?'], source:{label:'Swire Properties, Courvoisier Courts',url:'https://www.swireproperties.com/en/portfolio/past-developments/courvoisier-courts/'} },
  { slug:'one-tequesta-point', name:'One Tequesta Point', profile:'Island condominium', area:'Brickell Key', summary:'A Swire Properties residential project on Brickell Key; assess the specific unit and association records.', confirmed:['Swire Properties identifies One Tequesta Point as a Brickell Key development.','Its published portfolio describes a residential project on the island.'], questions:['What are the current budget, reserve and insurance records?','Which water views are visible from the actual unit?','What are the documented parking and use rights?'], source:{label:'Swire Properties, One Tequesta Point',url:'https://www.swireproperties.com/en/portfolio/past-developments/one-tequesta-point/'} },
  { slug:'500-brickell', name:'500 Brickell', profile:'Residential development', area:'Brickell core', summary:'A Related Group residential project in Brickell; compare unit layout and current association records.', confirmed:['Related Group lists 500 Brickell in its project portfolio.','The official portfolio describes a residential condominium project.'], questions:['What does the latest association budget include?','Which line and floor best match your light and noise needs?','What restrictions and assessment notices apply?'], source:{label:'Related Group, 500 Brickell',url:'https://relatedgroup.com/properties/500-brickell/'} },
  { slug:'residences-at-1428-brickell', name:'The Residences at 1428 Brickell', profile:'Residential development', area:'Brickell Avenue', summary:'A residential project promoted at 1428 Brickell Avenue; verify current stage and contractual specifications.', confirmed:['The official project site identifies its address as 1428 Brickell Avenue.','Project materials describe a residential tower concept.'], questions:['What is the current construction and contract status?','Which features are in the applicable offering documents?','What deposits and completion provisions apply?'], source:{label:'The Residences at 1428 Brickell, project site',url:'https://1428brickell.com/'} },
  { slug:'st-regis-residences-miami', name:'The St. Regis Residences Miami', profile:'Branded residential development', area:'South Brickell waterfront', summary:'A branded waterfront residence project; verify contract terms, service rights and project stage.', confirmed:['The official project site presents The St. Regis Residences Miami as a residential development.','Its project materials locate the development on Brickell’s waterfront.'], questions:['What is the present construction and delivery status?','Which branded services are contractual or separately charged?','What is the unit-specific view and insurance exposure?'], source:{label:'The St. Regis Residences Miami project site',url:'https://miamisrr.com/'} },
  { slug:'mercedes-benz-places-miami', name:'Mercedes-Benz Places Miami', profile:'Branded residential development', area:'Brickell', summary:'A Mercedes-Benz branded Brickell residential project; compare proposed services with offering documents.', confirmed:['Mercedes-Benz project materials identify a Miami residential development.','The official project site describes its Brickell location.'], questions:['What is the project’s current status and delivery schedule?','Which amenities and services are contractually included?','What are the deposit and association budget assumptions?'], source:{label:'Mercedes-Benz Places Miami project site',url:'https://miami.mercedesbenzplaces.com/'} },
  { slug:'2200-brickell', name:'2200 Brickell', profile:'Residential development', area:'South Brickell', summary:'A South Brickell residential project; compare its proposed product with existing condominium alternatives.', confirmed:['The official 2200 Brickell site identifies the project in Brickell.','Published materials present a residential development concept.'], questions:['What is the current construction or delivery stage?','Which floor plan and finish terms are contractual?','What budget and use restrictions apply to the exact unit?'], source:{label:'2200 Brickell project site',url:'https://2200brickell.com/'} },
  { slug:'mandarin-oriental-residences-miami', name:'The Residences at Mandarin Oriental Miami', profile:'Branded island development', area:'Brickell Key', summary:'A Swire Properties residential project on Brickell Key; verify current stage and service terms.', confirmed:['Swire Properties identifies The Residences at Mandarin Oriental Miami as a current development.','Its official portfolio locates the project on Brickell Key.'], questions:['What is the current stage and contractual completion position?','Which services and amenities are included in the offering?','How do deposits and projected carrying costs compare?'], source:{label:'Swire Properties, Mandarin Oriental residences',url:'https://www.swireproperties.com/en/portfolio/current-developments/the-residences-at-mandarin-oriental-miami/'} },
  { slug:'icon-brickell', name:'Icon Brickell', profile:'Residential development', area:'Brickell riverfront', summary:'A Related Group project in Brickell; assess exact tower, unit and current governing documents.', confirmed:['Related Group lists Icon Brickell among its residential projects.','The official project profile identifies its Brickell location.'], questions:['Which legal tower and association govern the unit?','What are the current fees, reserves and assessment notices?','Do written rental rules fit the planned use?'], source:{label:'Related Group, Icon Brickell',url:'https://relatedgroup.com/properties/icon-brickell/'} },
  { slug:'millecento-1100', name:'1100 Millecento', profile:'Residential development', area:'South Miami Avenue', summary:'A Related Group residential project; compare unit location and current association costs.', confirmed:['Related Group lists 1100 Millecento in its property portfolio.','The developer describes the project as a residential building.'], questions:['What are the current association budget and reserve records?','What rental and pet rules apply to the specific unit?','How do nearby streets affect the unit’s outlook?'], source:{label:'Related Group, 1100 Millecento',url:'https://relatedgroup.com/properties/1100-millecento/'} },
  { slug:'brickell-heights', name:'Brickell Heights', profile:'Residential development', area:'Central Brickell', summary:'A Related Group condominium project; confirm which residence and association documents apply.', confirmed:['Related Group identifies Brickell Heights in its development portfolio.','The official profile describes a residential Brickell project.'], questions:['Which building and association correspond to the unit?','What are current fees, assessments and inspection records?','Which amenities and parking rights are documented?'], source:{label:'Related Group, Brickell Heights',url:'https://relatedgroup.com/properties/brickell-heights/'} },
  { slug:'echo-brickell', name:'Echo Brickell', profile:'Residential tower', area:'Brickell Avenue', summary:'A residential high-rise on the east side of Brickell Avenue. The developer describes it as a 60-story tower.', confirmed:['The JDS Development portfolio identifies Echo Brickell as a residential project on the east side of Brickell Avenue.','Its published tower profile emphasizes residential design and shared amenities; actual unit features must be checked individually.'], questions:['What is the present association budget and reserve study?','Which parking and storage rights belong to the unit?','What do the current rental and pet rules say?'], source:{label:'JDS Development, Echo Brickell project',url:'https://jdsdevelopment.com/portfolio/echo-brickell'} },
  { slug:'brickell-flatiron', name:'Brickell Flatiron', profile:'Residential tower', area:'Brickell core', summary:'A condominium project by CMC Group in central Brickell.', confirmed:['CMC Group lists Brickell Flatiron among its Miami projects.','The building’s central location makes walking routes and street activity useful visit-day checks.'], questions:['Which association financials and inspection records are current?','How do the floor and line affect the view and noise?','What rules apply to this specific intended use?'], source:{label:'CMC Group, Brickell Flatiron',url:'https://www.cmcgroupmiami.com/projects/brickell-flatiron.html'} },
  { slug:'sls-lux', name:'SLS LUX Brickell', profile:'Luxury condominium', area:'Central Brickell', summary:'A Related Group condominium project near Brickell City Centre; specific residence rights and amenities need document review.', confirmed:['Related Group identifies SLS LUX as a luxury condominium in Brickell.','The developer highlights its proximity to Brickell City Centre and designer-led interiors.'], questions:['What services and costs apply to this legal unit?','Which amenities are available under current association rules?','What do current rental and pet documents permit?'], source:{label:'Related Group, SLS LUX project',url:'https://relatedgroup.com/properties/sls-lux/'} },
  { slug:'four-seasons-residences', name:'Four Seasons Residences Miami', profile:'Private residences', area:'Brickell Avenue', summary:'Four Seasons identifies a Miami private-residences component; specific unit rights require written confirmation.', confirmed:['Four Seasons describes a private residential tower in central Miami.','Its residence page notes 186 private residences; individual resale availability is not verified here.'], questions:['Which service access is included for this unit?','What do condominium documents say about assessments and reserves?','How are hotel and residential facilities governed?'], source:{label:'Four Seasons Private Residences Miami',url:'https://www.fourseasons.com/residences/private_residences/miami/'} },
  { slug:'una-residences', name:'Una Residences', profile:'Waterfront development', area:'South Brickell waterfront', summary:'A Brickell waterfront residential project with architecture promoted by the project website.', confirmed:['The project site identifies Adrian Smith + Gordon Gill Architecture as the design firm.','Project materials describe its waterfront Brickell setting.'], questions:['What is the current construction and delivery status?','Which features and fees are binding in the offering documents?','How will the specific unit’s exposure and flood insurance be assessed?'], source:{label:'Una Residences project site',url:'https://www.unaresidences.com/'} },
  { slug:'cipriani-residences-miami', name:'Cipriani Residences Miami', profile:'Branded residential development', area:'South Miami Avenue', summary:'A Cipriani branded residential project at the gateway to Brickell; published features may change during development.', confirmed:['The project website locates the development in Brickell and describes a hospitality-led residential concept.','Its contact page publishes the address 1420 South Miami Avenue.'], questions:['What is the current construction and contractual delivery position?','What services are included versus separately charged?','What do the final offering documents say about the residence?'], source:{label:'Cipriani Residences Miami project site',url:'https://ciprianiresidencesmiami.com/'} },
  { slug:'viceroy-brickell', name:'Viceroy Brickell Residences', profile:'Branded residential development', area:'Central Brickell', summary:'A Viceroy branded residential concept in central Brickell with proposed shared amenities.', confirmed:['The project site identifies its location as Brickell.','Published concept materials describe a pool, wellness spaces and social amenities.'], questions:['Are the proposed amenities finalized in the offering documents?','What are the current budget and completion milestones?','What are the actual unit-level service rights and fees?'], source:{label:'Viceroy Brickell Residences, official developer site',url:'https://viceroybrickellresidences.com/'} },
  { slug:'baccarat-residences-miami', name:'Baccarat Residences Miami', profile:'Waterfront residential development', area:'Brickell riverfront', summary:'A Baccarat branded residential project positioned by its materials near the Miami River and Biscayne Bay.', confirmed:['The developer project site describes a Brickell waterfront residence collection where the river meets the bay.','Its legal notice says the offering is governed by the developer prospectus; website descriptions are not contractual.'], questions:['What is the confirmed construction and delivery status?','How will waterfront exposure and insurance affect ownership cost?','Which amenities and rights are contractual for the unit?'], source:{label:'Baccarat Residences Miami developer site',url:'https://baccaratresidencesmiami.com/'} }
];

export const buildingBySlug = Object.fromEntries(buildings.map(b => [b.slug, b])) as Record<string, Building>;
