import { residentialGuides } from './residential-content';
export type Guide = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  intent: string;
  budget: string;
  type: string;
  lead: string;
  checks: string[];
  decision: string;
  sourceKeys?: ('condo' | 'tax' | 'law' | 'flood' | 'cfpb' | 'fannie' | 'dda')[];
};

// Editorial criteria, not search results or representations of current inventory.
const existingGuides: Guide[] = [
  { slug:'condos-for-sale', title:'Brickell condos for sale: a buyer’s starting point', eyebrow:'Start here', description:'Choose the location, ownership costs and building profile that fit before requesting current inventory.', intent:'condos', budget:'any', type:'condo', lead:'Tell us what a useful shortlist would include.', checks:['Separate Brickell Key, the bayfront, Brickell Avenue and the City Centre area by daily routine.','Compare all-in monthly cost, including association fees, taxes and insurance, rather than purchase price alone.','Request the current budget, reserves, special assessment and inspection records for each building before committing.'], decision:'The right shortlist starts with your budget, bedroom need and timeline. Public search results can be stale, so ask for availability that has been checked for your criteria.', sourceKeys:['condo','tax'] },
  { slug:'brickell-condos-under-1m', title:'Brickell condos under $1M: a realistic search framework', eyebrow:'Budget guide', description:'Use a sub-$1M ceiling to screen ownership costs, building condition and tradeoffs before seeing matched units.', intent:'under-1m', budget:'under-1m', type:'condo', lead:'Set your maximum budget and tell us which tradeoffs are acceptable.', checks:['Keep a reserve below the purchase ceiling for closing costs and post-close expenses.','A lower price does not imply a lower total monthly cost; ask for actual current assessments.','Decide whether size, parking, views, walkability or building age can move.'], decision:'A price cap is a search filter, not a promise that any specific building has an eligible unit today.', sourceKeys:['condo','tax'] },
  { slug:'brickell-condos-1m-2m', title:'Brickell condos from $1M to $2M', eyebrow:'Budget guide', description:'Compare layout, location and ongoing costs across Brickell’s mid-to-upper condo budget.', intent:'1m-2m', budget:'1m-2m', type:'condo', lead:'Describe the layout and building feel you want in the $1M–$2M range.', checks:['Compare floor plans by usable space and exposure, not bedroom labels alone.','Check whether parking, storage or other rights transfer with a unit.','Review current association finances and any planned capital work.'], decision:'Two homes in the same price band can have very different carrying costs and rules; request unit-specific documents before comparing value.', sourceKeys:['condo'] },
  { slug:'luxury-condos', title:'Luxury condos in Brickell: what to compare', eyebrow:'Elevated living', description:'Build a luxury shortlist around privacy, service, views and verifiable ownership costs.', intent:'luxury', budget:'2m-plus', type:'luxury condo', lead:'Tell us your priorities for service, privacy, views and timing.', checks:['Assess arrival, elevator access and privacy alongside the marketing amenity list.','Ask which services are included in fees and which are separately billed.','Compare view corridors and adjacent development on the specific floor and line.'], decision:'A brand or amenity does not replace a review of governing documents and unit-level due diligence.', sourceKeys:['condo'] },
  { slug:'penthouses', title:'Brickell penthouses: a buyer’s due diligence guide', eyebrow:'Top-floor search', description:'Understand the practical questions behind a Brickell penthouse search before requesting availability.', intent:'penthouse', budget:'2m-plus', type:'penthouse', lead:'Specify outdoor space, privacy, ceiling height and target completion date.', checks:['Confirm which terraces, rooftop areas and parking spaces are deeded, assigned or common.','Check mechanical systems, roof exposure and maintenance responsibility.','Request actual floor plans and views for the specific unit.'], decision:'Penthouse labels vary by building; verify the legal description and exclusive-use rights before treating an amenity as included.', sourceKeys:['condo'] },
  { slug:'waterfront-condos', title:'Brickell waterfront condos: view, exposure and risk', eyebrow:'Bayfront search', description:'Compare Brickell bayfront living with an eye on exposure, insurance and the view from a specific unit.', intent:'waterfront', budget:'any', type:'waterfront condo', lead:'Tell us whether direct bay views, access or a particular building matter most.', checks:['Distinguish bayfront address from a direct unobstructed view.','Check the address in FEMA’s map and obtain current insurance terms for the building and unit.','Ask about balcony conditions, façade projects and future neighboring construction.'], decision:'Only unit-level evidence can confirm a lasting view; public building photos are no substitute.', sourceKeys:['flood','condo'] },
  { slug:'new-construction', title:'New construction condos in Brickell', eyebrow:'Construction guide', description:'Compare proposed projects and resale homes using delivery timing, deposits, documents and uncertainty.', intent:'new-construction', budget:'any', type:'new construction', lead:'Tell us your delivery flexibility and whether a completed home is an option.', checks:['Separate announced, under-construction and delivered projects.','Read developer offering documents for deposits, completion conditions and changes to plans.','Compare projected association fees with actual resale building budgets.'], decision:'Marketing plans and renderings may change. Confirm project status and contractual terms directly with the developer and independent counsel.', sourceKeys:['law'] },
  { slug:'brickell-key', title:'Buying a condo on Brickell Key', eyebrow:'Area guide', description:'Evaluate Brickell Key as a distinct island setting close to the mainland Brickell core.', intent:'brickell-key', budget:'any', type:'condo', lead:'Share your building preferences and the daily access you need.', checks:['Test your real commute across the bridge at the times you travel.','Compare each building’s association costs and policies separately.','Check flood, insurance and building-specific assessment documents.'], decision:'A quieter setting may suit some buyers; building documents and an on-site visit resolve the details that a neighborhood label cannot.', sourceKeys:['condo','flood'] },
  { slug:'brickell-avenue', title:'Brickell Avenue condo buying guide', eyebrow:'Area guide', description:'A practical way to compare buildings along Brickell Avenue without treating the corridor as one uniform market.', intent:'brickell-avenue', budget:'any', type:'condo', lead:'Tell us the segment of Brickell Avenue and building style you prefer.', checks:['Visit the exact entrance and check walking routes to your usual destinations.','Check the specific unit’s orientation and surrounding parcels.','Review budget, reserves, assessments and house rules at the building level.'], decision:'Street address alone does not tell you the view, traffic exposure or monthly carry.', sourceKeys:['condo'] },
  { slug:'foreign-buyers', title:'Brickell condos for foreign buyers', eyebrow:'International buyers', description:'Plan the buying process around financing, documentation, cross-border funds and ownership costs.', intent:'foreign-buyer', budget:'any', type:'condo', lead:'Tell us your country, funding method and whether you can visit before closing.', checks:['Ask a lender early about documentation and down-payment requirements for your profile.','Discuss title structure and tax consequences with licensed Florida and home-country advisers.','Arrange independent legal review and verify transfer instructions by a known phone number.'], decision:'Nationality does not determine a universal loan, tax or visa outcome. Seek individual professional advice before sending funds.', sourceKeys:['law','tax'] },
  { slug:'hoa-fees', title:'Brickell condo HOA fees: what the number leaves out', eyebrow:'Ownership cost', description:'Read association fees alongside budgets, reserve studies, assessments and the services included.', intent:'hoa-fees', budget:'any', type:'condo', lead:'Name the buildings you want compared and we’ll ask for current association figures.', checks:['Request the adopted budget and current assessment schedule.','Find out which insurance, utilities, parking and services the fee covers.','Review reserve study, milestone inspection summary where applicable and recent meeting minutes.'], decision:'No generic per-square-foot fee is reliable across buildings. Compare current documents for the specific unit.', sourceKeys:['condo','law'] },
  { slug:'property-taxes', title:'Brickell condo property taxes after purchase', eyebrow:'Ownership cost', description:'Estimate post-purchase taxes with county tools and understand why the seller’s bill may be misleading.', intent:'property-taxes', budget:'any', type:'condo', lead:'Share your target purchase range for a tax-aware carrying-cost shortlist.', checks:['Use the Miami-Dade Property Appraiser estimator rather than extrapolating the seller’s tax bill.','Ask about reassessment, exemptions and portability only where applicable to your circumstances.','Budget for taxes alongside HOA fees, insurance and mortgage payments.'], decision:'County estimates are estimates; the actual assessment and exemptions can differ.', sourceKeys:['tax'] },
  { slug:'closing-costs', title:'Closing costs for a Brickell condo purchase', eyebrow:'Transaction guide', description:'Plan for transaction expenses and confirm the allocation with your closing agent and lender.', intent:'closing-costs', budget:'any', type:'condo', lead:'Tell us your price range and payment method to build a focused question list.', checks:['Request a written estimate from the title company or closing attorney.','Ask your lender for a Loan Estimate if financing.','Confirm prorations, association approval fees and any special assessments in the contract.'], decision:'There is no safe universal percentage for every Brickell purchase; contract terms and financing change the total.', sourceKeys:['law'] },
  { slug:'financing', title:'Financing a Brickell condo', eyebrow:'Mortgage guide', description:'Assess both borrower qualification and building eligibility before relying on a mortgage scenario.', intent:'financing', budget:'any', type:'condo', lead:'Tell us cash or mortgage, expected down payment and purchase horizon.', checks:['Seek a lender familiar with Florida condo project review.','Ask whether the building’s insurance, reserves, litigation or occupancy affects the chosen loan.','Compare rate, cash to close and total monthly housing cost.'], decision:'Preapproval of the borrower does not guarantee financing for a particular condo project.', sourceKeys:['condo'] },
  { slug:'brickell-vs-downtown-miami', title:'Brickell vs Downtown Miami for condo buyers', eyebrow:'Neighborhood comparison', description:'Compare street life, commute, building choice and practical ownership questions.', intent:'comparison', budget:'any', type:'condo', lead:'Describe your commute and lifestyle priorities for a two-area shortlist.', checks:['Walk both areas at the times you would actually use them.','Compare a specific building and unit rather than two neighborhood averages.','Check transit, street noise, views and ownership documents side by side.'], decision:'The best fit depends on your routine and the unit, not a universal neighborhood winner.', sourceKeys:['condo'] },
  { slug:'best-condos-in-brickell', title:'Best condos in Brickell: build your own shortlist', eyebrow:'Selection framework', description:'A criteria-based approach to “best” that does not invent rankings or inventory.', intent:'best-condos', budget:'any', type:'condo', lead:'Rank your top three priorities and request a tailored comparison.', checks:['Choose your non-negotiables: budget, commute, size, privacy or service.','Compare association financials and inspections before amenities.','Visit shortlisted buildings and check real unit availability.'], decision:'No building is best for every buyer. We organize a decision around your priorities instead of paid or unsupported rankings.', sourceKeys:['condo'] },
  { slug:'buying-a-condo-in-brickell', title:'How to buy a condo in Brickell', eyebrow:'Buyer journey', description:'From search criteria to building documents, contract review and closing.', intent:'buyer-journey', budget:'any', type:'condo', lead:'Tell us which stage you are at, from first search to ready to offer.', checks:['Define must-haves and maximum monthly carrying cost.','Confirm financing strategy and request checked availability.','Before contract deadlines, review disclosures, inspections, association records and closing figures with advisers.'], decision:'A clear process protects time and helps buyers compare the actual total cost of a specific unit.', sourceKeys:['condo','law'] },
  { slug:'brickell-key-vs-brickell', title:'Brickell Key vs mainland Brickell', eyebrow:'Area comparison', description:'Island pace and mainland convenience compared through routine, access and building-level diligence.', intent:'area-comparison', budget:'any', type:'condo', lead:'Tell us which daily routes and neighborhood feel matter most.', checks:['Try the bridge crossing during your expected commute.','Compare amenities and association charges in individual buildings.','Test walkability to the destinations you use weekly.'], decision:'Neither area guarantees lower costs or a quieter unit. Visit and compare exact buildings.', sourceKeys:['condo','flood'] },
  { slug:'brickell-condos-2m-plus', title:'Brickell condos above $2M', eyebrow:'Budget guide', description:'A high-budget search that weighs floor plan, view protection, discretion and carrying cost.', intent:'2m-plus', budget:'2m-plus', type:'luxury condo', lead:'Set a purchase ceiling and tell us your view, size and privacy requirements.', checks:['Look at the actual line, floor and view corridor.','Ask how staff, services and capital projects affect recurring expenses.','Check deeded rights, storage and parking for each unit.'], decision:'High asking prices do not validate an individual unit’s condition or the association’s finances.', sourceKeys:['condo'] },
  { slug:'condo-reserves', title:'Brickell condo reserves and special assessments', eyebrow:'Building diligence', description:'Questions to ask before a low monthly fee or a large amenities list becomes a decision factor.', intent:'reserves', budget:'any', type:'condo', lead:'Name the building to request the most recent budget and reserve documents.', checks:['Review the current reserve study and adopted budget.','Check assessment notices and board meeting minutes.','Ask a qualified inspector or attorney to explain major repair obligations.'], decision:'Reserve adequacy is building-specific; a public guide cannot verify an association’s current books.', sourceKeys:['condo','law'] },
  { slug:'condo-inspections', title:'Milestone inspections for Brickell condo buyers', eyebrow:'Building diligence', description:'Locate inspection summaries and understand the related repair and budget questions.', intent:'inspections', budget:'any', type:'condo', lead:'Specify the building and we’ll include inspection records in the diligence checklist.', checks:['Ask whether the building has a required milestone inspection.','Read the inspector-prepared summary, phase-two status if any, and board response.','Link reported repairs to budgets, funding plans and potential assessments.'], decision:'An inspection schedule or report is not a warranty. Review the current record with independent experts.', sourceKeys:['condo','law'] },
  { slug:'condo-insurance', title:'Condo insurance in Brickell: two policies to examine', eyebrow:'Ownership cost', description:'Distinguish association coverage from your unit policy and assess deductibles and flood exposure.', intent:'insurance', budget:'any', type:'condo', lead:'Tell us which buildings are on your list for insurance-document questions.', checks:['Request the association insurance summary and current budget.','Obtain a unit-owner quote based on the actual unit and lender requirements.','Check mapped flood risk and exclusions with a licensed insurance professional.'], decision:'A building-wide premium does not show your personal coverage or out-of-pocket exposure.', sourceKeys:['condo','flood'] },
  { slug:'condo-documents', title:'Brickell condo documents to request before an offer', eyebrow:'Document checklist', description:'A practical checklist for association finances, rules, inspection records and contract review.', intent:'documents', budget:'any', type:'condo', lead:'Send the building name and your timing to receive a focused diligence checklist.', checks:['Get declaration, bylaws, rules and current budget.','Request financial statements, reserve study and any applicable milestone summary.','Ask about pending litigation, assessments, rental and pet rules in current association documents.'], decision:'Policies change; neither a third-party directory nor an old listing substitutes for current written association records.', sourceKeys:['condo','law'] },
  { slug:'brickell-commute', title:'Brickell condo commute and location checklist', eyebrow:'Lifestyle guide', description:'Judge real travel patterns from a building entrance rather than a neighborhood pin.', intent:'commute', budget:'any', type:'condo', lead:'Share your key destinations and travel times for an area-led shortlist.', checks:['Test a weekday morning and evening route from candidate addresses.','Check walking access, transit, ride-hailing pickup and parking entry.','Compare routes during rain and event traffic.'], decision:'A few blocks can change the daily experience; validate a route yourself before paying a location premium.' },
  { slug:'first-time-condo-buyer', title:'First-time Brickell condo buyer checklist', eyebrow:'First purchase', description:'A simple sequence for budget, building due diligence and a protected offer.', intent:'first-time', budget:'any', type:'condo', lead:'Tell us what you already know about budget and financing.', checks:['Calculate cash to close plus a contingency, not just a down payment.','Get financing guidance before pursuing a specific building.','Ask your agent and counsel to track document and inspection deadlines.'], decision:'Buy the whole cost and obligation package, not just the apartment interior.', sourceKeys:['condo','tax','law'] },
  { slug:'brickell-condo-investment', title:'Buying a Brickell condo as an investment', eyebrow:'Investment lens', description:'Model carrying costs and written rental rules without projecting returns or assumed occupancy.', intent:'investment', budget:'any', type:'condo', lead:'Share your investment horizon and rental plan so rules can be checked.', checks:['Obtain the current association rental policy in writing for each candidate.','Include vacancies, taxes, management, insurance, HOA and possible assessments in a sensitivity model.','Seek local legal and tax advice on ownership and leasing obligations.'], decision:'No rental permission, income or return is implied for any named building on this site.', sourceKeys:['condo','tax'] },
  { slug:'new-construction-vs-resale', title:'New construction vs resale condos in Brickell', eyebrow:'Decision guide', description:'Compare delivery certainty, fees, warranties and available documents.', intent:'new-vs-resale', budget:'any', type:'condo', lead:'Tell us whether your move date allows a project under construction.', checks:['For new projects, examine offering documents and deposit protections with counsel.','For resale, inspect the actual unit and current association records.','Compare projected costs with proven budgets and known repair plans.'], decision:'A future rendering and a completed resale home require different evidence.', sourceKeys:['condo','law'] },
  { slug:'brickell-condo-closing-process', title:'Brickell condo closing process: buyer checklist', eyebrow:'Closing process', description:'Track lender, title, association and document deadlines from accepted offer to closing.', intent:'closing-process', budget:'any', type:'condo', lead:'Start with the actual contract dates and the parties responsible for each task.', checks:['Confirm inspection, financing and condominium document deadlines in the signed contract.','Ask the closing agent for itemized figures and verified wire instructions.','Compare the final Closing Disclosure with your earlier Loan Estimate when financing.'], decision:'The contract and transaction professionals determine your actual deadlines; this guide is a planning checklist, not a legal timeline.', sourceKeys:['law','cfpb'] },
  { slug:'brickell-condo-special-assessments', title:'Brickell condo special assessments: what to verify', eyebrow:'Ownership cost', description:'Check assessment notices, board records, funding plans and contract allocation before comparing offers.', intent:'special-assessments', budget:'any', type:'condo', lead:'Ask about both approved charges and proposed capital work for the specific association.', checks:['Request current notices, adopted budgets and recent board minutes.','Match the stated assessment to payment dates and any unit-level balance.','Have the closing agent and counsel confirm contract allocation and estoppel details.'], decision:'A low monthly fee does not establish that future capital spending is covered; only current association records can establish a specific obligation.', sourceKeys:['condo','law'] },
  { slug:'brickell-condo-rental-restrictions', title:'Brickell condo rental restrictions: buyer questions', eyebrow:'Use and leasing', description:'Verify current leasing rules, approval requirements and unit-specific limitations before assuming rental income.', intent:'rental-restrictions', budget:'any', type:'condo', lead:'Tell us your intended use and ask for the current written association rules.', checks:['Request declaration, bylaws, rules and any amendments relevant to leasing.','Ask about minimum lease terms, frequency, caps and registration in current documents.','Check whether a proposed use is allowed for the exact unit and ownership situation.'], decision:'This site does not assert that any named building permits short-term or other rental use.', sourceKeys:['condo','law'] },
  { slug:'brickell-condo-pet-rules', title:'Brickell condo pet rules: how to check before buying', eyebrow:'Building rules', description:'Use current association documents to assess pet limits and approval steps for a specific unit.', intent:'pet-rules', budget:'any', type:'condo', lead:'Describe your pet and request written rules from each building on your list.', checks:['Review declaration, rules and amendments rather than old listing descriptions.','Check any stated size, number, registration and common-area requirements.','Discuss individual legal accommodation questions with a qualified professional instead of assuming a blanket outcome.'], decision:'Pet policies can differ by building and may change; verify current documents before committing.', sourceKeys:['condo','law'] },
  { slug:'brickell-condo-application-approval', title:'Brickell condo application and approval process', eyebrow:'Association process', description:'Plan for building-specific application documents, fees and timing without assuming a universal approval period.', intent:'application-approval', budget:'any', type:'condo', lead:'Ask the actual association or management company for its current buyer package.', checks:['Get the current application, fee schedule and document checklist.','Confirm the association review step against your contract and closing calendar.','Keep lender and closing agent informed if association documents or approvals are outstanding.'], decision:'Every building’s procedure and transaction timetable must be confirmed directly; no universal approval time is represented.', sourceKeys:['condo','law'] },
  { slug:'brickell-condo-mortgage-requirements', title:'Brickell condo mortgage requirements: buyer and building', eyebrow:'Mortgage guide', description:'Understand borrower preapproval, condo project review, insurance and cash-to-close questions.', intent:'mortgage-requirements', budget:'any', type:'condo', lead:'Speak with a lender about both your financial profile and the specific project.', checks:['Request a Loan Estimate for your financing scenario.','Ask the lender which project documents and insurance information it needs.','Verify whether reserves, repairs or litigation affect the selected loan program.'], decision:'Borrower preapproval alone does not confirm that a specific condo project meets a lender’s requirements.', sourceKeys:['cfpb','fannie'] },
  { slug:'cash-vs-financing-brickell-condo', title:'Cash vs financing a Brickell condo', eyebrow:'Funding comparison', description:'Compare liquidity, cash to close, financing costs and project eligibility before choosing a funding path.', intent:'cash-vs-financing', budget:'any', type:'condo', lead:'Compare written numbers for your actual purchase rather than a general rate example.', checks:['For financing, compare Loan Estimates and total ownership cost.','For cash, preserve a reserve for closing, taxes, insurance and potential assessments.','Ask counsel and your closing agent about the contract and timing implications of each route.'], decision:'Cash can remove lender project review from a transaction, but it does not replace building due diligence or legal review.', sourceKeys:['cfpb','condo'] }
];

export const guides: Guide[] = [...existingGuides, ...residentialGuides];

export const guideBySlug = Object.fromEntries(guides.map(g => [g.slug, g])) as Record<string, Guide>;
