// Original editorial prompts. Columns describe evidence to request, never inventory or quoted fees.
export const matrices: Record<string,{heading:string; intro:string; rows:[string,string,string][]}> = {
  'condos-for-sale': { heading:'Build a shortlist in three passes',intro:'A broad search becomes actionable only when each candidate passes the same tests.',rows:[['Place','Route from the actual entrance to your weekly destinations','Avoid paying for an area you will rarely use'],['Unit','Floor plan, orientation, parking and natural light at a viewing','A building profile cannot describe every line'],['Association','Budget, reserve study, assessments and rules','Ownership costs and permitted use differ by building']] },
  'brickell-condos-under-1m': { heading:'Make a sub-$1M ceiling work',intro:'The search price is only one constraint. Set a monthly and cash-to-close ceiling as well.',rows:[['Purchase ceiling','Your lender or cash plan plus a separate closing-cost reserve','Prevents a full-price offer from exhausting available cash'],['Monthly ceiling','Mortgage scenario, county tax estimate, unit policy and current HOA statement','A less expensive unit may cost more each month'],['Flexibility','Rank size, parking, views and age before viewing','A clear tradeoff prevents random shortlists']] },
  'brickell-condos-1m-2m': { heading:'Compare value within the band',intro:'Focus on rights and usability that can differ even between similar asking prices.',rows:[['Actual layout','Measured floor plan and in-person walkthrough','Bedroom count alone hides usable space'],['Rights','Deed or written assignment for parking and storage','Marketing descriptions may not transfer a property right'],['Carry','Current fee statement and assessment history','Similar prices can imply different ownership costs']] },
  'luxury-condos': { heading:'Test the luxury promise',intro:'Service and privacy should be evidenced for the exact residence.',rows:[['Arrival and access','Visit at different hours; inspect elevator arrangements','Privacy varies with floor and shared uses'],['Service scope','Written inclusions and separate fee schedule','An amenity can be available yet separately charged'],['View','Specific floor and line, surrounding parcels','A tower’s advertised panorama may not be this unit’s view']] },
  'penthouses': { heading:'Penthouse rights worth proving',intro:'Labels alone do not establish control over terraces, equipment or parking.',rows:[['Outdoor space','Legal description and limited-common-element documents','Exclusive-use rights may differ from ownership'],['Roof systems','Inspection and maintenance allocation','Top-floor exposure changes the diligence scope'],['Privacy','Floor plan, elevator and neighboring mechanical areas','The top floor is not automatically secluded']] },
  'waterfront-condos': { heading:'What “waterfront” should mean to you',intro:'Separate a water-facing address from unit-level view and carrying-cost evidence.',rows:[['View','Visit the exact unit; inspect orientation and future adjacent parcels','Not every home in a waterfront tower faces the water'],['Exposure','FEMA address lookup and insurance quotes','Mapped risk and coverage require unit and building review'],['Structure','Façade, balcony and reserve records','Waterfront maintenance can affect future spending']] },
  'new-construction': { heading:'Compare proposals with completed homes',intro:'A project brochure and an existing unit offer different kinds of certainty.',rows:[['Status','Developer update and current permit or delivery documentation','Proposed completion is not a guaranteed move-in date'],['Money','Deposit schedule and escrow terms reviewed by counsel','Cash may be tied up before occupancy'],['Budget','Estimated association budget versus a resale association’s adopted budget','Forecast fees are not actual operating costs']] },
  'brickell-key': { heading:'Test the island fit',intro:'A visit should cover everyday logistics as well as the setting.',rows:[['Bridge access','Drive or walk at your commute hour','Your routine determines the cost of a single access point'],['Building choice','Separate budgets and rules for each association','An island does not share a single HOA policy'],['Exposure','Flood map, insurance and maintenance review','Location alone does not quantify your risk']] },
  'brickell-avenue': { heading:'Compare exact stretches of the avenue',intro:'The corridor changes block by block and floor by floor.',rows:[['Entrance','Walk the block and test parking ingress','Street feel and access vary even on one road'],['Orientation','Look at the specific line and surrounding sites','An address cannot guarantee light or quiet'],['Association','Current budget, assessments and rules','Tower age and operating plan are building-specific']] },
  'foreign-buyers': { heading:'Coordinate the cross-border workstreams',intro:'Start early because banking, ownership and travel documents move on different schedules.',rows:[['Funding','Lender checklist or proof-of-funds requirements','A US purchase may need extra origin-of-funds records'],['Title and tax','Florida counsel and advisers in your country','Entity ownership and future sale outcomes are individual'],['Execution','Closing agent’s verified wire instructions','Independently call a known number before transfer']] },
  'hoa-fees': { heading:'Read the HOA figure in context',intro:'The statement for one unit should be read beside association finances.',rows:[['Included services','Current fee schedule and budget line items','Insurance, utilities and amenities vary'],['Future spend','Reserve study, inspection summary and meeting minutes','A low fee may coexist with future capital needs'],['One-off amounts','Assessment notices and closing estoppel information','An assessment can alter the first year’s cost']] },
  'property-taxes': { heading:'Estimate your own tax position',intro:'A seller’s historical bill can reflect different exemptions and valuation.',rows:[['Starting input','Target purchase price in county estimator','The prior owner’s bill is a poor proxy'],['Exemptions','Confirm eligibility with county or tax adviser','Residence and ownership details affect the outcome'],['Scenario','Revisit the estimate with your lender and closing agent','Use a buffer because an estimate is not a final bill']] },
  'closing-costs': { heading:'Get an itemized estimate',intro:'Who pays which charge depends on your contract and funding.',rows:[['Lender costs','Loan Estimate for your exact financing scenario','Rate and loan structure change cash to close'],['Title and recording','Written estimate from closing agent','Allocation is negotiated and contract-specific'],['Condo charges','Association approval, estoppel and assessment documents','One-time association charges may be material']] },
  'financing': { heading:'Two approvals to think about',intro:'The borrower and the condo project can be evaluated separately.',rows:[['Borrower','Lender preapproval and proof of funds','Defines a practical search ceiling'],['Project','Lender condo questionnaire and insurance/financial review','A building may not fit a chosen loan program'],['Payment','Rate scenario plus taxes, HOA and insurance','The true monthly cost determines comfort']] },
  'brickell-vs-downtown-miami': { heading:'Use one scorecard for both areas',intro:'Compare equal housing types and visit at the same times.',rows:[['Daily trip','Door-to-door travel at your usual hour','Map distance misses actual delays'],['Environment','Street visit morning, evening and weekend','Area labels hide block-level noise and activity'],['Ownership','Actual unit and association documents','Neighborhood averages do not buy or maintain your unit']] }
};
