import type { Guide } from './content';

type Section = { heading: string; text: string; checks: string[] };
type Page = {
  slug: string; title: string; eyebrow: string; description: string; intent: string; type: string;
  intro: string; sections: [Section, Section]; decision: string;
  related: { label: string; href: string }[]; sourceKeys?: Guide['sourceKeys'];
};

// Editorial decision frameworks. No unit availability, project delivery, fee or rule is inferred.
export const residentialPages: Page[] = [
  { slug:'branded-residences',title:'Branded residences in Brickell: service and ownership',eyebrow:'Property type',description:'Compare hospitality promises, contractual service rights, privacy and recurring costs at branded Brickell developments.',intent:'branded-residence',type:'branded residence',intro:'A familiar name may describe design, hospitality or management, but it does not establish a particular unit’s service rights. Compare the legal residence, the actual service schedule and the fees behind the brand.',sections:[
    {heading:'Separate brand from the contract',text:'Ask how the brand participates in the project, which services are included, which are optional, and who may change the program. For an uncompleted project, use the current offering documents rather than renderings.',checks:['Identify the legal entity responsible for each service.','Compare included and separately billed services.','Verify access, amenity and termination terms in writing.']},
    {heading:'Compare like-for-like ownership',text:'Set the service premium beside privacy, floor plan and association costs in an unbranded alternative. A brand may matter differently to a full-time resident and an occasional visitor.',checks:['Request the budget and any service-fee schedule.','Check rental and guest-use provisions for the exact unit.','Confirm current project status and view orientation.']}],decision:'Buy the documented residence and service package, not an assumed hotel experience.',related:[{label:'Luxury residences',href:'/luxury-condos/'},{label:'Condo versus branded',href:'/condo-vs-branded-residence/'},{label:'Mandarin Oriental profile',href:'/buildings/mandarin-oriental-residences-miami/'}],sourceKeys:['condo'] },
  { slug:'high-rise-residences',title:'Brickell high-rise residences: floor, access and exposure',eyebrow:'Property type',description:'Evaluate tower living through floor and line, vertical access, building systems and total ownership cost.',intent:'high-rise',type:'high-rise residence',intro:'A skyline address does not tell you how a particular residence lives. Floor, orientation, elevator access, parking entry and shared systems can change the experience inside the same tower.',sections:[
    {heading:'Test the daily route',text:'Start at the street entrance. Compare elevator capacity, arrival, parking and access to ordinary destinations before selecting a floor. Visit at the times you expect to use the building.',checks:['Walk the entrance-to-unit journey.','Compare actual floor and line for noise, light and view.','Verify parking and storage rights.']},
    {heading:'Inspect the shared structure',text:'High-rise ownership includes the condition of systems beyond the apartment. Review current inspection, reserve, insurance and capital-project records with qualified professionals.',checks:['Request current building inspection documents.','Connect planned repairs to reserves and assessments.','Get unit-specific insurance and monthly cost estimates.']}],decision:'Compare the unit and the vertical building as one ownership decision.',related:[{label:'Brickell Core area',href:'/brickell-core/'},{label:'Building index',href:'/buildings/'},{label:'Ownership economics',href:'/ownership-costs/'}],sourceKeys:['condo'] },
  { slug:'resale-properties',title:'Resale residences in Brickell: condition and certainty',eyebrow:'Property type',description:'Compare completed Brickell homes using inspections, ownership records, association history and closing timing.',intent:'resale',type:'resale',intro:'A resale lets you inspect a real residence and request an operating association’s records. It also brings the specific unit’s maintenance history, alterations and known building projects into the decision.',sections:[
    {heading:'Examine what exists',text:'Walk the exact unit and commission suitable inspections. Compare the marketed floor plan with the legal description, improvements and actual parking or storage allocations.',checks:['Inspect condition and alterations with a qualified professional.','Confirm legally assigned outdoor, parking and storage space.','Ask which repairs or appliances may need replacement.']},
    {heading:'Use the association history',text:'Request current budgets, reserves, minutes, insurance, inspection reports and assessment notices. Align document delivery and approval steps with your contract deadlines.',checks:['Read adopted budgets and recent board decisions.','Separate an approved charge from a proposed project.','Confirm approval and closing dates in the contract.']}],decision:'A completed home offers more observable evidence, but its condition and liabilities still need independent review.',related:[{label:'New construction versus resale',href:'/new-construction-vs-resale/'},{label:'Special assessments',href:'/brickell-condo-special-assessments/'},{label:'Closing process',href:'/brickell-condo-closing-process/'}],sourceKeys:['condo'] },
  { slug:'pre-construction',title:'Pre-construction residences in Brickell',eyebrow:'Property type',description:'Understand deposits, offering documents, delivery uncertainty and proposed costs before selecting a future residence.',intent:'pre-construction',type:'new construction',intro:'A pre-construction residence is a contractual future product. The project site may show a design vision, while the signed agreement defines the rights, deposit schedule and change provisions.',sections:[
    {heading:'Review what is being promised',text:'Ask the developer for the latest offering documents and current project stage. Have independent counsel compare the unit plan, finish schedule, deposit terms and permitted changes to your expectations.',checks:['Confirm the current stage directly with the developer.','Map deposits and escrow provisions.','Review substitutions, deadlines and termination terms.']},
    {heading:'Compare a future home with today’s alternatives',text:'Projected association costs and service descriptions are estimates. Compare a future unit’s timing and flexibility with an inspectable resale or delivered residence.',checks:['Budget for a changed delivery date.','Compare proposed costs with adopted resale budgets.','Confirm lender requirements for your planned financing.']}],decision:'Treat delivery, specifications and projected charges as questions for the actual offering and contract.',related:[{label:'Pre-construction buying process',href:'/pre-construction-buying-process/'},{label:'New construction',href:'/new-construction/'},{label:'New versus resale',href:'/new-construction-vs-resale/'}],sourceKeys:['law'] },
  { slug:'primary-residence-brickell',title:'Buying a primary residence in Brickell',eyebrow:'Buyer objective',description:'Choose a Brickell home around everyday routes, usable space, monthly cost and building reliability.',intent:'primary-residence',type:'flexible',intro:'A primary home needs to work on an ordinary weekday. Rank commute, floor plan, natural light and recurring expense before deciding whether an island, waterfront or core location fits.',sections:[
    {heading:'Make the daily routine concrete',text:'Test school, work and errands from actual building entrances at your normal hours. Confirm parking and elevator access, guest rules and what the unit layout supports.',checks:['Test two real travel windows.','Measure usable rooms, storage and working space.','Compare entry, elevators and parking.']},
    {heading:'Keep monthly ownership comfortable',text:'Model principal and interest if financing, association charges, post-purchase taxes, insurance and a repair reserve. Discuss any owner-occupancy tax question with the county and your adviser.',checks:['Request unit-level costs and current association records.','Plan cash to close plus a separate reserve.','Verify occupancy-related eligibility independently.']}],decision:'Choose a verified home and ownership budget that can support your everyday life.',related:[{label:'South Brickell',href:'/south-brickell/'},{label:'How to buy in Brickell',href:'/buying-a-home-in-brickell/'},{label:'Ownership economics',href:'/ownership-costs/'}],sourceKeys:['tax'] },
  { slug:'second-home-brickell',title:'Buying a second home in Brickell',eyebrow:'Buyer objective',description:'Plan occasional use around building access, absence management, insurance, financing and documented guest rules.',intent:'second-home',type:'flexible',intro:'A second home has different practical demands from an everyday residence. Consider arrival, security, property care during absences and whether guests or rentals are permitted under current written rules.',sections:[
    {heading:'Design for periods away',text:'Ask how the building handles access, deliveries and maintenance requests. Visit the unit’s actual entry and review insurance implications of intermittent occupancy with a licensed provider.',checks:['Confirm the actual guest and access procedures.','Plan property checks during extended absences.','Get coverage advice for your use pattern.']},
    {heading:'Price and document the intended use',text:'Taxes, loan terms and association rules may depend on actual use. Never assume the property can produce rental income to fund the second home.',checks:['Request current rental and pet rules.','Model full carrying cost without rental income.','Discuss taxes and financing with independent advisers.']}],decision:'The value of a second home depends on reliable access and a cost plan that works even when it is empty.',related:[{label:'Brickell Key',href:'/brickell-key/'},{label:'Rental restrictions',href:'/brickell-condo-rental-restrictions/'},{label:'Insurance guide',href:'/condo-insurance/'}],sourceKeys:['tax','condo'] },
  { slug:'investment-properties-brickell',title:'Brickell residential property for investment-oriented buyers',eyebrow:'Buyer objective',description:'Test rental permission, total costs, vacancy and exit assumptions without inventing returns or availability.',intent:'investment',type:'flexible',intro:'An investment purchase starts with permission and numbers, not projected rent. Compare actual written use rules, unit condition and an expense scenario that includes vacancy, management and unexpected building work.',sections:[
    {heading:'Verify the planned use',text:'Request the declaration and current amendments for the exact residence. Confirm minimum lease term, approval requirements and any legal or lender limits before underwriting an income case.',checks:['Confirm rental terms in current written rules.','Check whether a unit-specific restriction or lease exists.','Request professional advice for the intended use.']},
    {heading:'Stress-test the carrying cost',text:'Use a sensitivity table with taxes, insurance, association charges, management, vacancy, repairs and assessments. Consider resale liquidity and the likely buyer pool without assuming appreciation.',checks:['Model a period with no tenant.','Include repair and assessment contingencies.','Compare financed and cash scenarios separately.']}],decision:'No rent, occupancy, yield or permitted rental use is represented for any named property.',related:[{label:'Rental restrictions',href:'/brickell-condo-rental-restrictions/'},{label:'Cash versus financing',href:'/cash-vs-financing-brickell-condo/'},{label:'Ownership economics',href:'/ownership-costs/'}],sourceKeys:['condo','tax'] },
  { slug:'brickell-core',title:'Brickell Core and Financial District residences',eyebrow:'Area guide',description:'Compare residential buildings near Brickell City Centre and the financial district through access, density and unit exposure.',intent:'brickell-core',type:'flexible',intro:'This editorial submarket centers on the mixed-use Brickell City Centre and financial-district streets. It is a location lens, not a formal legal neighborhood boundary. Dense residential towers sit among office, retail and transit destinations.',sections:[
    {heading:'Where the streets change the decision',text:'Walk from the candidate entrance toward the destinations you actually use. Central addresses may make errands easy while individual streets differ in curb access, activity and arrival.',checks:['Locate the exact entrance relative to Brickell City Centre.','Test pedestrian routes and parking access.','Visit at weekday and evening hours.']},
    {heading:'Match the building stock to your purpose',text:'Established and newer high-rise residences serve different price, design and document profiles. Compare a specific resale unit with current association records; ask a development for its present offering terms.',checks:['Compare Reach and Rise as individual buildings.','Check floor and line for outlook and noise.','Request current carrying-cost evidence.']}],decision:'A central address helps narrow the map; it cannot replace a unit and building review.',related:[{label:'Reach profile',href:'/buildings/reach-brickell-city-centre/'},{label:'Rise profile',href:'/buildings/rise-brickell-city-centre/'},{label:'High-rise residences',href:'/high-rise-residences/'}],sourceKeys:['dda'] },
  { slug:'south-brickell',title:'South Brickell residences: a location framework',eyebrow:'Area guide',description:'Explore the southern Brickell corridor through building placement, waterfront access and everyday routes.',intent:'south-brickell',type:'flexible',intro:'South Brickell is used here as an editorial search area south of the busiest commercial core, including parts of the Brickell Avenue corridor. Exact boundaries vary by source; assess each address and its connection to the waterfront and main streets.',sections:[
    {heading:'Test distance and exposure',text:'A southern address may change how you reach work, shops and waterfront paths. Walk the actual route and examine unit orientation instead of treating the entire corridor as one residential experience.',checks:['Measure routes from the building entrance.','Check water-facing and street-facing lines separately.','Inspect access at your usual hours.']},
    {heading:'Compare different project stages',text:'The area includes established residential towers and promoted developments. Existing homes permit condition and association review; future homes call for a contract and timing review.',checks:['Compare a resale with a proposed residence.','Request current insurance and repair records where applicable.','Verify a development’s current stage independently.']}],decision:'Use a location preference to build a shortlist, then validate the exact unit and ownership documents.',related:[{label:'Una profile',href:'/buildings/una-residences/'},{label:'2200 Brickell profile',href:'/buildings/2200-brickell/'},{label:'Resale residences',href:'/resale-properties/'}],sourceKeys:['dda'] },
  { slug:'brickell-bay-drive',title:'Brickell Bay Drive residential guide',eyebrow:'Area guide',description:'Assess bay-edge addresses through unit views, waterfront exposure, access and building-specific costs.',intent:'brickell-bay-drive',type:'flexible',intro:'Brickell Bay Drive is an eastern Brickell street near Biscayne Bay. Its proximity to water is a geographic starting point, not proof that a particular apartment has a direct or protected bay view.',sections:[
    {heading:'Separate street from unit orientation',text:'Compare each candidate’s floor, line, actual window view and adjacent sites. Walk the street and test the journey to destinations west of Brickell Avenue.',checks:['Obtain current unit-specific view evidence.','Walk the entrance-to-transit and errand routes.','Review nearby parcels without assuming a permanent view.']},
    {heading:'Price exposure and operations',text:'Ask for current association insurance, inspection and capital-work records. Obtain a unit policy quote that reflects the exact residence, not a generic waterfront label.',checks:['Check the exact address with FEMA tools.','Request current budgets and deductible details.','Confirm monthly cost and planned work.']}],decision:'A bay-edge address can shape the search but only the actual residence and records resolve the purchase.',related:[{label:'Waterfront residences',href:'/waterfront-condos/'},{label:'Insurance guide',href:'/condo-insurance/'},{label:'Brickell Avenue',href:'/brickell-avenue/'}],sourceKeys:['flood','dda'] },
  { slug:'north-brickell-miami-river',title:'North Brickell and Miami River edge residences',eyebrow:'Area guide',description:'Compare river-edge residential positions, downtown access and exact-building exposure at Brickell’s northern edge.',intent:'north-brickell',type:'flexible',intro:'This editorial area follows the Brickell side of the Miami River near the northern edge of the district. The river crossings connect it to Downtown, while the precise street and tower determine access, noise and water orientation.',sections:[
    {heading:'Understand the edge condition',text:'Walk from the building to the bridge, transit and daily services. Compare river-facing, inland and higher-floor units separately and check the actual entrance experience.',checks:['Test the intended river crossing at commute hours.','Confirm actual unit views and surrounding parcels.','Check walking and vehicle access from the address.']},
    {heading:'Read the ownership records',text:'River proximity requires address-specific insurance questions. A branded or established tower may have very different service rights and association finances.',checks:['Request the current building insurance summary.','Compare unit and association expense schedules.','Verify project status for any development marketed nearby.']}],decision:'River frontage and downtown access are useful search criteria, not unit-level guarantees.',related:[{label:'Baccarat profile',href:'/buildings/baccarat-residences-miami/'},{label:'Icon Brickell profile',href:'/buildings/icon-brickell/'},{label:'Brickell vs Downtown',href:'/brickell-vs-downtown-miami/'}],sourceKeys:['flood','dda'] },
  { slug:'waterfront-vs-inland-brickell',title:'Waterfront vs inland Brickell residences',eyebrow:'Buyer comparison',description:'Compare real unit views, insurance and daily access with inland alternatives at a consistent total budget.',intent:'waterfront-comparison',type:'flexible',intro:'The waterfront decision is about a specific residence and its cost, not a label on a building. Compare one water-oriented unit with an inland alternative using the same layout, commute and ownership-cost criteria.',sections:[
    {heading:'Value the experience you can verify',text:'Ask what water is visible from the living areas and how surrounding sites might change the view. Compare arrival and routine routes in both buildings.',checks:['Use current unit-level view evidence.','Test real commute and outdoor access.','Confirm whether the water is visible from primary rooms.']},
    {heading:'Keep the cost comparison fair',text:'Ask about association insurance, deductibles, façade or balcony work and unit coverage at each address. Total monthly carrying cost can shift the apparent premium.',checks:['Obtain comparable insurance quotes.','Review current budgets and assessments.','Decide what view premium fits your priorities.']}],decision:'Choose the residence whose verified experience and total cost fit your needs.',related:[{label:'Waterfront residences',href:'/waterfront-condos/'},{label:'Brickell Bay Drive',href:'/brickell-bay-drive/'},{label:'Ownership economics',href:'/ownership-costs/'}],sourceKeys:['flood'] },
  { slug:'condo-vs-branded-residence',title:'Condo vs branded residence in Brickell',eyebrow:'Buyer comparison',description:'Compare a documented residence, hospitality-style services, privacy and recurring cost without assuming brand benefits.',intent:'brand-comparison',type:'flexible',intro:'A branded residence is often a condominium too. The useful comparison is an ordinary service model versus a project with brand-associated design or hospitality, using the actual documents for each home.',sections:[
    {heading:'Describe the service in contractual terms',text:'List every service that is included, optional or unavailable. Compare guest access, privacy and management rules for the specific unit.',checks:['Read current service and association agreements.','Ask which charges are separate from regular fees.','Check how services may change over time.']},
    {heading:'Compare the same ownership basket',text:'Review unit layout, legal rights, financing, taxes and association finances in both candidates. A branded marketing premium does not imply a different resale outcome.',checks:['Compare total monthly carrying costs.','Match floor and view quality on actual units.','Request current budgets and capital-work records.']}],decision:'Compare verifiable services and actual homes, not a brand name against an abstract condo category.',related:[{label:'Branded residences',href:'/branded-residences/'},{label:'Luxury residences',href:'/luxury-condos/'},{label:'Condo buyer hub',href:'/condos-for-sale/'}] },
  { slug:'buying-a-home-in-brickell',title:'How to buy a home or residence in Brickell',eyebrow:'Buyer journey',description:'A residential purchase framework from objectives and funding to area, building, unit diligence and closing.',intent:'home-buyer-journey',type:'flexible',intro:'Begin with how you will use the property: full-time home, second home or investment-oriented purchase. Then select an area, building and actual residence. The right evidence differs for completed resales and future developments.',sections:[
    {heading:'Set the decision and budget',text:'Define your must-haves, purchase ceiling, cash to close and comfortable monthly carry. Choose a funding plan and identify any use requirement such as a pet, guest access or rental permission.',checks:['Choose a primary, second-home or investment objective.','Decide the acceptable monthly carrying cost.','State timing, area and non-negotiables.']},
    {heading:'Move from shortlist to closing',text:'Request checked options matched to your brief. Verify the specific unit, project stage, title, association documents, inspections, insurance and contract deadlines with independent professionals.',checks:['Visit the actual unit and entrance.','Read current governing documents and budgets.','Track financing, approval and closing milestones.']}],decision:'This site provides decision research and inquiries; it does not publish live listings or guarantee a match.',related:[{label:'Property types',href:'/#property-types'},{label:'Buyer guides index',href:'/buyer-guides/'},{label:'Ownership economics',href:'/ownership-costs/'}],sourceKeys:['cfpb'] },
  { slug:'pre-construction-buying-process',title:'Brickell pre-construction buying process',eyebrow:'Buyer journey',description:'Follow project stage, offering documents, staged deposits, changes and financing before a future-home commitment.',intent:'pre-construction-process',type:'new construction',intro:'A purchase before completion involves a different evidence set from an existing residence. Ask for current developer materials and have independent counsel review the actual agreement before committing deposits.',sections:[
    {heading:'Identify the exact contract product',text:'Confirm the legal project, unit plan, planned amenities, deposit schedule and escrow terms. A brochure or rendering cannot replace the offering documents.',checks:['Read the offering and purchase agreement.','Map each deposit and due date.','Check specifications and allowed changes.']},
    {heading:'Prepare for changing timelines',text:'Delivery may shift; confirm current status directly with the developer and plan financing and housing arrangements with that uncertainty in mind.',checks:['Ask how delays and termination are addressed.','Compare projected fees with available resale evidence.','Recheck loan and insurance terms nearer closing.']}],decision:'Verify contractual protections and project progress for the specific opportunity; no completion date is implied here.',related:[{label:'Pre-construction residences',href:'/pre-construction/'},{label:'New construction',href:'/new-construction/'},{label:'Resale comparison',href:'/new-construction-vs-resale/'}],sourceKeys:['law'] },
  { slug:'ownership-costs',title:'Brickell home ownership costs: the complete budget',eyebrow:'Ownership economics',description:'Model cash to close, monthly carrying costs and a repair reserve across Brickell residences and project stages.',intent:'ownership-costs',type:'flexible',intro:'Purchase price is one number in a larger ownership decision. A Brickell residence may add association and service charges, property taxes, insurance, financing, special assessments and furnishing or repair costs. A new development may show projections rather than an operating budget.',sections:[
    {heading:'Calculate funds needed to close',text:'Start with deposit and down payment, lender or cash financing choice, title and closing charges, insurance funding, prorations and association application costs. Ask the appropriate closing and lending professionals for actual figures.',checks:['Request a written settlement or Loan Estimate where applicable.','Include deposits and closing funds on one timeline.','Keep a separate post-close reserve.']},
    {heading:'Calculate ongoing ownership',text:'Compare current or projected association charges, post-purchase tax estimates, unit and master insurance, utilities, financing and planned capital work. Stress-test a second home or investment without assumed rental income.',checks:['Review adopted budgets and any assessments.','Obtain address-specific insurance guidance.','Allow for furnishings, repairs and future fee changes.']}],decision:'Use a unit-specific total-cost worksheet; no site-wide estimate can establish the cost of a particular home.',related:[{label:'Property taxes',href:'/property-taxes/'},{label:'Insurance',href:'/condo-insurance/'},{label:'Closing costs',href:'/closing-costs/'},{label:'Reserves',href:'/condo-reserves/'}],sourceKeys:['tax','cfpb','condo'] }
];

export const residentialGuides: Guide[] = residentialPages.map(p => ({
  slug:p.slug,title:p.title,eyebrow:p.eyebrow,description:p.description,intent:p.intent,budget:'any',type:p.type,
  lead:p.intro,checks:[p.sections[0].checks[0],p.sections[0].checks[1],p.sections[1].checks[0]],
  decision:p.decision,sourceKeys:p.sourceKeys
}));

export const residentialDetail: Record<string,{ headline:string; intro:string; sections:Section[]; brief:string; related:Page['related'] }> = Object.fromEntries(residentialPages.map(p => [p.slug, {
  headline:p.eyebrow==='Area guide'?'Start with the exact address.':p.eyebrow==='Buyer comparison'?'Compare two verifiable choices.':p.eyebrow==='Buyer objective'?'Work backward from your intended use.':p.eyebrow==='Ownership economics'?'Model the full cost of ownership.':'Define the residence before the shortlist.',intro:p.intro,sections:p.sections,brief:p.decision,related:p.related
}]));

export const additionalDetails: typeof residentialDetail = {
  'brickell-key': {headline:'Island location, individual building decisions.',intro:'Brickell Key is an island east of mainland Brickell, linked by a bridge. Swire Properties documents a range of established residential buildings there and an additional branded development. The island address alone cannot describe a particular residence, its view or its current association costs.',sections:[{heading:'Test the bridge and daily access',text:'Walk from the exact entrance toward mainland destinations and test the bridge at the hours you expect to travel. An island setting may suit a buyer seeking a distinct arrival, while commute patterns remain individual.',checks:['Test pedestrian and vehicle routes.','Compare each building’s entrance and parking.','Verify actual unit outlook and island access.']},{heading:'Compare established and future residences',text:'Brickell Key One, Courts Brickell Key and One Tequesta Point provide distinct established building profiles; the Mandarin Oriental residences have a separate development profile. Confirm current unit inventory and project status directly.',checks:['Request current association financials for a resale.','Read offering documents for a proposed home.','Compare insurance and carrying cost.']}],brief:'Name the actual building and intended use before requesting matched options.',related:[{label:'Brickell Key One',href:'/buildings/brickell-key-one/'},{label:'Mandarin Oriental residences',href:'/buildings/mandarin-oriental-residences-miami/'},{label:'Brickell Key versus mainland',href:'/brickell-key-vs-brickell/'},{label:'Waterfront residence decisions',href:'/waterfront-condos/'},{label:'Review ownership costs',href:'/ownership-costs/'}]},
  'brickell-avenue': {headline:'A corridor, not one uniform home market.',intro:'Brickell Avenue runs through different parts of the district. A building’s street address may conceal meaningful differences in waterfront proximity, street activity, entrance conditions and unit orientation. Compare exact blocks and residences.',sections:[{heading:'Walk the relevant segment',text:'Define whether the address sits nearer the core or the southern stretch. Check your actual route to shops, work and transport, then inspect loading and parking access.',checks:['Compare core and south travel routes.','Visit at your typical hours.','Confirm floor and line exposure.']},{heading:'Compare building stage and ownership',text:'An established residence provides current association records; a development requires its latest offering terms and a delivery-risk discussion. Do not infer availability from a building profile.',checks:['Review insurance and repair records for resale.','Check deposits and projected fees for a development.','Verify unit-level parking and views.']}],brief:'Tell us the Avenue segment, property type and monthly-cost preference.',related:[{label:'Echo Brickell',href:'/buildings/echo-brickell/'},{label:'South Brickell',href:'/south-brickell/'},{label:'Branded residences',href:'/branded-residences/'},{label:'High-rise residence decisions',href:'/high-rise-residences/'},{label:'Read condo documents',href:'/condo-documents/'}]},
  'brickell-vs-downtown-miami': {headline:'Compare actual daily routes across the river.',intro:'Brickell and Downtown are connected but offer different address-level routines. Use a matched pair of real residences to compare commute, building documentation, entrance experience and total costs instead of general neighborhood rankings.',sections:[{heading:'Choose two real addresses',text:'Walk the route at the time you expect to travel. Check crossings, transit and errands from each building entrance, not from a map pin.',checks:['Time the actual commute.','Compare street activity by time of day.','Check the unit’s floor and line.']},{heading:'Hold the budget and evidence constant',text:'Compare current association charges, insurance, taxes and repair work at each candidate. A broad area average cannot reveal a particular association’s obligations.',checks:['Use unit-specific total-cost figures.','Request current building documents.','Rank the routine you value.']}],brief:'Share your destinations and the buildings you would compare.',related:[{label:'North Brickell river edge',href:'/north-brickell-miami-river/'},{label:'Brickell Core',href:'/brickell-core/'},{label:'Ownership economics',href:'/ownership-costs/'}]},
  'brickell-key-vs-brickell': {headline:'Island arrival versus mainland routes.',intro:'Brickell Key has a distinct bridge connection; mainland Brickell offers several different street and transit contexts. Select actual buildings on both sides and compare access, unit orientation and document-backed costs.',sections:[{heading:'Test your routine',text:'Travel from each entrance to destinations you use, including the bridge at representative times. Compare walkability without assuming either side is uniformly quiet or busy.',checks:['Time the bridge crossing.','Compare walks to essentials.','Inspect each building entrance.']},{heading:'Compare the homes',text:'Evaluate unit view, legal rights, insurance, association finances and inspection records. Include future development timing if a candidate has not been delivered.',checks:['Review each current document package.','Obtain insurance guidance for each address.','Compare like-for-like monthly costs.']}],brief:'Name an island and mainland building to compare.',related:[{label:'Brickell Key',href:'/brickell-key/'},{label:'Brickell Core',href:'/brickell-core/'},{label:'Courts Brickell Key',href:'/buildings/courts-brickell-key/'}]},
  'new-construction-vs-resale': {headline:'Compare two different kinds of evidence.',intro:'A completed resale allows unit inspection and current operating association review. A future development relies on offering documents, deposits and projected costs. Compare the same ownership goal while acknowledging these different information sets.',sections:[{heading:'A resale: inspect the actual home',text:'Request current records, inspect the unit, and review repairs, insurance and closing schedules.',checks:['Inspect unit condition.','Read adopted budgets and assessments.','Confirm transaction deadlines.']},{heading:'A development: review contractual delivery',text:'Ask for current project stage, offering terms, deposit schedule and change rights. Estimated fees are not an operating history.',checks:['Review offering and deposit documents.','Plan for timing changes.','Compare projected monthly cost with resale evidence.']}],brief:'Tell us your move date and tolerance for development uncertainty.',related:[{label:'Resale properties',href:'/resale-properties/'},{label:'Pre-construction',href:'/pre-construction/'},{label:'Closing process',href:'/brickell-condo-closing-process/'}]}
};
